apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app-tier
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: frontend
          image: talalalredaacr.azurecr.io/frontendimage:latest
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_BASE_URL
              value: http://172.213.226.248:8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: app-tier
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
